### ISSUE TITLE
Problems with big endian

### ISSUE THREAD

**Issue by laufhannes** [mrihtar/Garmin-FIT#1]
The perl module has some problems with big endian values. 
- The parser will fail for big endian files with array-valued fields (such as for hrv)
  - see Runalyze/Runalyze#1797 for a related issue
  - see https://github.com/Runalyze/Runalyze/commit/73a59bae079e45af12d6923451cdfefb67906518 for a fix
- The parser will fail on big endian systems
  - see Runalyze/Runalyze#1875 for a related issue
  - message numbers will be wrong
  - for a fix:
    - `$endian != $my_endian` should be `$endian` ([#L4780](https://github.com/mrihtar/Garmin-FIT/blob/4a8df447236e0d1617da0fd129564d9bc51328b7/Garmin/FIT.pm#L4780), [#L4828](https://github.com/mrihtar/Garmin-FIT/blob/4a8df447236e0d1617da0fd129564d9bc51328b7/Garmin/FIT.pm#L4828), [#L4868](https://github.com/mrihtar/Garmin-FIT/blob/4a8df447236e0d1617da0fd129564d9bc51328b7/Garmin/FIT.pm#L4868)) 
    - add `$v = reverse $v if ref $desc->{endian_converter} eq 'ARRAY';` to [#L4927](https://github.com/mrihtar/Garmin-FIT/blob/4a8df447236e0d1617da0fd129564d9bc51328b7/Garmin/FIT.pm#L4927)

I can add a pull request for this, but I don't have a big endian system to check and a final confirmation that the last point fixes wrong ordering of arrayed-valued fields is still missing (see https://github.com/Runalyze/Runalyze/issues/1875#issuecomment-234050418).

PS: Thanks for having a repo for Kiyokazu's perl module!

**Comment by mrihtar** [comment]
Kiyokazu created a patch (https://github.com/mrihtar/Garmin-FIT/commit/d951563c43a9111f2ea5d3b127553141b66818e0), which should fix this problem.

**Comment by mrihtar** [comment]
I am closing this, as there are no other complaints about this patch for now.
