### ISSUE TITLE
Can't convert fit-File from Wahoo Elemnt

### ISSUE THREAD

**Issue by streamtec** [mrihtar/Garmin-FIT#11]
first thank you to mrihtar for develop and programing this utility.

I use the perl-file fit2slf.pl to convert my workouts from fit-file-format to slf-file-format.
After converting, I import them into the Sigma Data Center. This works very fine till the last firmware update of the wahoo elemnt.
When I try to convert the fit-file now, I get an error:
"Can't use an undefined value as a HASH reference at ./fit2slf.pl line 414".

Can you please take a look at this problem?

I can sent you an example file in the old and the new export format of the wahoo elemnt.

best regards streamtec

**Comment by mrihtar** [comment]
Hi!
Please send me both files and I'll see what's wrong. I also recommend you download the latest version of the scripts and library, because the code in the current version of fit2slf.pl at line 414 can't produce the error you described.

**Comment by streamtec** [comment]
Hi,
I will attache the two Files.

ELEMNT_old.fit is the File that can be converted,
ELEMNT_new.fit is the File that produce the Error (both contained in the wahooELEMNT.zip)

**Comment by streamtec** [comment]
Sorry my mistake,
I closed the issue

**Comment by streamtec** [comment]
Hi,
I will attache the two Files.

ELEMNT_old.fit is the File that can be converted,
ELEMNT_new.fit is the File that produce the Error (both contained in the wahooELEMNT.zip)

best regards
streamtec

**Comment by mrihtar** [comment]
Please try the new version of fit2slf.pl and FIT.pm on some of your new Elemnt files and if it's OK, please close the issue.

**Comment by streamtec** [comment]
many thanks to mrihtar for the good and quickly support !!!!!!
I've tested the new versions and they works fine.
