### ISSUE TITLE
import virtual Ride from Zwift via Garmin

### ISSUE THREAD

**Issue by sirtheta** [mrihtar/Garmin-FIT#14]
Today I tried to import a virtual ride from zwift. The file was uploaded to garmin and I downloaded it from there as usual. But then I am always geting an error. (line 260)
I am looking forward to also import my virtual rides.
Thanks for your work on this tool!
[2269877207.zip](https://github.com/mrihtar/Garmin-FIT/files/1443218/2269877207.zip)

**Comment by mrihtar** [comment]
I think this should be fixed now, although I don't recommend biking under the water, especially on remote South Pacific islands :-).

**Comment by sirtheta** [comment]
It is working very good! Thanks a lot! 
BTW, biking in watopia is great fun!
