### ISSUE TITLE
Newer profiles

### ISSUE THREAD

**Issue by dirkhh** [mrihtar/Garmin-FIT#16]
I have FIT files that show `protocol ver: 1.00, profile ver: 20.44` and when dumping them there are quite a few unknown values... what's the process by which this library gets updated to newer versions?

**Comment by mrihtar** [comment]
Thanks for the notice about the new version. For the update I typically check and compare official SDK documentation and change FIT.pm accordingly. It would help me though, if you could send me an example of such .FIT file (20.44) to see if there are any additional fields not mentioned in the latest SDK.

**Comment by dirkhh** [comment]
Since the files contain user specific and device specific information, I'd prefer not to attach one here. Happy to send it to you, though.

**Comment by mrihtar** [comment]
Sure. You can find my e-mail by looking at https://api.github.com/repos/mrihtar/garmin-FIT/commits. I will keep the file private.

**Comment by mrihtar** [comment]
I've updated FIT module to the latest version of SDK (20.72.00). Your file looks much better now - there is only one unknown field (#88) left in records, which appears only sometimes. There are other unknown fields here and there, but this has always been so and I can't do much more than this.
