### ISSUE TITLE
fit2gpx.pl writes lat="0" lon="0" if position is not defined in fit file

### ISSUE THREAD

**Issue by konzeptix** [mrihtar/Garmin-FIT#17]
In gpx files generated by fit2gpx.pl, I find points with zero longitude and zero latitude. Identifing the respective point in the fitdump.pl output via timestamp (timezone considered correctly) shows, that location information was not provided in this case. See below for respective data from dump and gpx file.

fitdump.pl output:
record (20, type: 1, length: 19 bytes):
  timestamp (253-1-UINT32): 2019-02-13T12:39:05 (918992345)
  distance (5-1-UINT32): 8060.45 m (806045)
  altitude (2-1-UINT16): 521.8 m (5109)
  xxx87 (87-1-UINT16): 0
  xxx88 (88-1-UINT16): 300
  heart_rate (3-1-UINT8): 157 bpm (157)
  cadence (4-1-UINT8): 86 rpm (86)
  temperature (13-1-SINT8): 17 deg.C (17)
  fractional_cadence (53-1-UINT8): 0.00 rpm (0)

corresponding fit2gpx.pl output
 `<trkpt lat="0" lon="0">
                <ele>521.8</ele>
                <time>2019-02-13T11:39:05Z</time>
                <extensions>
                    <gpxtpx:TrackPointExtension>
                        <gpxtpx:hr>157</gpxtpx:hr>
                        <gpxtpx:cad>86</gpxtpx:cad>
                        <gpxtpx:atemp>17</gpxtpx:atemp>
                    </gpxtpx:TrackPointExtension>
                </extensions>
            </trkpt>`

[example.zip](https://github.com/mrihtar/Garmin-FIT/files/2907559/example.zip)

**Comment by mrihtar** [comment]
Fixed: I stopped processing records where no latitude or longitude are defined (i.e. skip them).
