### ISSUE TITLE
Developer data with fit_base_type_id=0=enum is not respected

### ISSUE THREAD

**Issue by laufhannes** [mrihtar/Garmin-FIT#20]
Suunto does write a *subjective feeling* to the activity summary in their fit files as developer data. However, this module does not respect the developer field definition because of an "*invalid base type*". I don't see why `fit_base_type_id=0=enum` should be invalid.

[suunto-dev-field-enum.zip](https://github.com/mrihtar/Garmin-FIT/files/3251396/suunto-dev-field-enum.zip)

Uncommenting the if block at https://github.com/mrihtar/Garmin-FIT/blob/800fffa2d2aea33f7e99d1041839da7b28a54c3a/Garmin/FIT.pm#L6843 does temporarily solve the issue.

**Comment by mrihtar** [comment]
Thanks for noticing this. Should be fixed now.
