### ISSUE TITLE
Incorrect Altitude in Sigma SLF file

### ISSUE THREAD

**Issue by ainthek** [mrihtar/Garmin-FIT#29]
I have converted FIT to SLF and viewed in sigma, see altitude displayed 
<img width="1728" alt="Screenshot 2020-10-22 at 19 19 11" src="https://user-images.githubusercontent.com/559519/96907763-f9e5b780-149b-11eb-833a-f5f429af1523.png">

Original FIT (from SUUNTO watch) and converted files are here:
https://github.com/ainthek/map-projects/tree/master/misc/fit2slf-bug

Thanx for your time and work.

fit2slf 2.14  Copyright (c) 2016-2020 Matjaz Rihtar  (Sep 7, 2020)
Garmin::FIT  Copyright (c) 2010-2017 Kiyokazu Suto
FIT protocol ver: 2.4, profile ver: 21.32

**Comment by mrihtar** [comment]
Altitude difference should now be correctly calculated . To fix starting altitude (it might not be present in the first few records due to sensor delay), set "home_altitude" in *.ini to known starting altitude.
