### ISSUE TITLE
fit2slf.pl command does not work

### ISSUE THREAD

**Issue by heini123** [mrihtar/Garmin-FIT#4]
Hi, I saw your entry in the German MTB news forum. Great tool. After installing Strawberry Perl on Win64 and the 3 Modules (and a reboot of the PC), I get the following error message. Any idea what went wrong ? Thank you.

C:>cd Strawberry

C:\Strawberry>dir
 Volume in Laufwerk C: hat keine Bezeichnung.
 Volumeseriennummer: 2099-FEC9

 Verzeichnis von C:\Strawberry

16.10.2016  13:57    <DIR>          .
16.10.2016  13:57    <DIR>          ..
16.10.2016  12:22    <DIR>          c
16.10.2016  12:29    <DIR>          cpan
11.05.2016  00:56            11.807 DISTRIBUTIONS.txt
16.10.2016  12:43            42.513 fit2slf.ini
16.10.2016  12:40           511.021 fit2slf.pl
16.10.2016  12:44            99.829 fitdump.pl
16.10.2016  12:54    <DIR>          Garmin
16.10.2016  12:23    <DIR>          licenses
16.10.2016  12:22    <DIR>          perl
16.10.2016  12:23             2.119 README.txt
16.10.2016  12:23            23.783 relocation.txt
15.10.2016  17:07           314.842 test.fit
16.10.2016  12:23    <DIR>          win32
               7 Datei(en),      1.005.914 Bytes
               8 Verzeichnis(se), 141.501.394.944 Bytes frei

C:\Strawberry>fitdump.pl
Bareword found where operator expected at C:\Strawberry\fitdump.pl line 6, near ""en" class"
        (Missing operator before class?)
Bareword found where operator expected at C:\Strawberry\fitdump.pl line 22, near "<title>Garmin"
        (Missing operator before Garmin?)
Can't modify numeric lt (<) in scalar assignment at C:\Strawberry\fitdump.pl line 6, near ""en" class"
syntax error at C:\Strawberry\fitdump.pl line 6, near ""en" class"
Unrecognized character \xC2; marked by <-- HERE after at master <-- HERE near column 44 at C:\Strawberry\fitdump.pl line 22.

C:\Strawberry>fit2slf.pl
Bareword found where operator expected at C:\Strawberry\fit2slf.pl line 6, near ""en" class"
        (Missing operator before class?)
Bareword found where operator expected at C:\Strawberry\fit2slf.pl line 22, near "<title>Garmin"
        (Missing operator before Garmin?)
Can't modify numeric lt (<) in scalar assignment at C:\Strawberry\fit2slf.pl line 6, near ""en" class"
syntax error at C:\Strawberry\fit2slf.pl line 6, near ""en" class"
Unrecognized character \xC2; marked by <-- HERE after at master <-- HERE near column 44 at C:\Strawberry\fit2slf.pl line 22.

C:\Strawberry>fit2slf.pl test.fit
Bareword found where operator expected at C:\Strawberry\fit2slf.pl line 6, near ""en" class"
        (Missing operator before class?)
Bareword found where operator expected at C:\Strawberry\fit2slf.pl line 22, near "<title>Garmin"
        (Missing operator before Garmin?)
Can't modify numeric lt (<) in scalar assignment at C:\Strawberry\fit2slf.pl line 6, near ""en" class"
syntax error at C:\Strawberry\fit2slf.pl line 6, near ""en" class"
Unrecognized character \xC2; marked by <-- HERE after at master <-- HERE near column 44 at C:\Strawberry\fit2slf.pl line 22.

**Comment by heini123** [comment]
Some additional infos: The Perl installation is fine (perl -v) and a test script : #!/bin/perl -w
print "Hello World"; also works without problems

**Comment by mrihtar** [comment]
Hello @heini123! Judging by the size of files "fit2slf.pl", "fitdump.pl" and others from your listing I would say you don't have the "raw" source files, but files with HTML code. You should download either release from [Releases](https://github.com/mrihtar/Garmin-FIT/releases) page or download raw files (click on file, then click or right click on [Raw](https://github.com/mrihtar/Garmin-FIT/raw/master/fit2slf.pl) and save file.
Otherwise these tools work fine with latest Strawberry Perl on Win64.

**Comment by heini123** [comment]
it works, excellent, thank you :-)
