### ISSUE TITLE
fit2gpx.pl didnt parse fit file at all

### ISSUE THREAD

**Issue by ghost** [mrihtar/Garmin-FIT#8]
I was just playing around with some sample FIT files and for most of them it "somehow" works but one was not parsed at all -> It is attached -> Maybe could you check on it what happened ?

Thanks,

TkTz
[Laufen.zip](https://github.com/mrihtar/Garmin-FIT/files/731869/Laufen.zip)

**Comment by mrihtar** [comment]
I added limited support for non Garmin FIT files. In your case the file was from Suunto and was missing fields here and there (for example, not every record had latitude and longitude fields, which I set to 0 in such cases). Scripts now parse your file and produce some output, but to properly parse this kind of file would require additional logic and/or more initial values in .INI file.

**Comment by ghost** [comment]
Thanks for the improvement - I will check that out soon !
